<?php
	$db_server = "";	// Domännamn för MySQLservern
	$db_login = "";							// Användarnamn för MySQLservern
	$db_password = ""; 						// Lösenord för MySQLservern
	$db_name = "dishreview";// Vilken databas
	/*
	$db_server = "mlab1.msi.vxu.se";	// Domännamn för MySQLservern
	$db_login = "gj222af";							// Användarnamn för MySQLservern
	$db_password = "sbfa7qc0"; 						// Lösenord för MySQLservern
	$db_name = "gj222af";// Vilken databas
	
	$db_server = "wadur.com.mysql";	// Domännamn för MySQLservern
	$db_login = "wadur";							// Användarnamn för MySQLservern
	$db_password = "GuwRXUCv"; 						// Lösenord för MySQLservern
	$db_name = "wadur_com";// Vilken databas
	*/
?>
